#!/usr/bin/env python3
"""Generate .build/sbo_layout.h from the device's own vmlinux BTF.

The module includes no socket or cgroup headers. Our common-6.12.69 tree
differs from the shipped kernel inside types reachable from struct sock and
struct cgroup (the device uses Android KABI reserve slots in mm_struct and
task_struct as anonymous unions, and keeps netns_mib.tls_statistics although
its config.gz says CONFIG_TLS is not set), so a module-local struct sock can
never be deduplicated against the device BTF: the tracepoint's `struct sock *`
would point at the module's copy and the verifier rejects bpf_sk_storage_get()
on it ("sock but sock_common is expected"). With struct sock opaque, pahole
resolves it to the device type, as for sbo_identity_bridge.

Every field the module reads through these opaque types comes from here,
taken from the device BTF:
  sock         __sk_common.skc_family, sk_kern_sock      (inet filter)
  task_struct  cgroups                                   (own-cgroup gate)
  css_set      dfl_cgrp
  cgroup       kn
  kernfs_node  name
"""
from btfutil import here, load_base, find_structs, member, resolve

base, _ = load_base()


def struct_ids(name):
    ids = find_structs(base, name, 1, len(base) + 1)
    assert ids, name
    return ids


def struct_id(name):
    ids = struct_ids(name)
    assert len(ids) == 1, (name, ids)
    return ids[0]


def byte_offset(struct, path, size=None, kind=None):
    bit, bits, tid = member(base, struct_id(struct), path)
    assert bits == 0 and bit % 8 == 0, (struct, path, "not byte aligned")
    if size is not None:
        t = base[resolve(base, tid)]
        assert t["kind"] == kind and t["value"] == size, (struct, path, t)
    return bit // 8


POINTER = 2
sock = struct_id("sock")
fam_bit, fam_bits, fam_type = member(base, sock, ["__sk_common", "skc_family"])
fam_int = base[resolve(base, fam_type)]
assert fam_bits == 0 and fam_bit % 8 == 0 and fam_int["kind"] == 1 and fam_int["value"] == 2
kern_bit, kern_bits, _ = member(base, sock, ["sk_kern_sock"])
assert kern_bits == 1, "sk_kern_sock must be a 1-bit field"


def pointer_offset(struct, field):
    # The device BTF may carry more than one definition of a struct (it has
    # two task_struct entries); every one must agree.
    offsets = set()
    for sid in struct_ids(struct):
        bit, bits, tid = member(base, sid, [field])
        assert bits == 0 and bit % 8 == 0
        assert base[resolve(base, tid)]["kind"] == POINTER, (struct, field)
        offsets.add(bit // 8)
    assert len(offsets) == 1, (struct, field, offsets)
    return offsets.pop()


out = here / ".build"
out.mkdir(exist_ok=True)
values = {
    "SBO_SKC_FAMILY_OFFSET": fam_bit // 8,
    "SBO_SK_KERN_SOCK_BYTE": kern_bit // 8,
    "SBO_SK_KERN_SOCK_SHIFT": kern_bit % 8,
    "SBO_TASK_CGROUPS_OFFSET": pointer_offset("task_struct", "cgroups"),
    "SBO_CSS_SET_DFL_CGRP_OFFSET": pointer_offset("css_set", "dfl_cgrp"),
    "SBO_CGROUP_KN_OFFSET": pointer_offset("cgroup", "kn"),
    "SBO_KERNFS_NODE_NAME_OFFSET": pointer_offset("kernfs_node", "name"),
}
(out / "sbo_layout.h").write_text(
    "/* Generated by gen_layout.py from the device vmlinux BTF. Do not edit. */\n"
    + "".join(f"#define {k} {v}\n" for k, v in values.items())
)
print(" ".join(f"{k}={v}" for k, v in values.items()))
