#!/usr/bin/env python3
"""Generate .build/sbo_sock_layout.h from the device's own vmlinux BTF.

The module must not include <net/sock.h>: our common-6.12.69 tree differs
from the device kernel inside types reachable from struct sock (the device
uses Android KABI reserve slots in mm_struct/task_struct as anonymous unions,
and keeps netns_mib.tls_statistics), so a module-local definition of struct
sock can never be deduplicated against the device BTF. The tracepoint's
`struct sock *` would then point at the module's copy, and the verifier
rejects bpf_sk_storage_get() on it. With struct sock left opaque, pahole
resolves it to the device type, exactly as for sbo_identity_bridge.

The two facts the module reads from a socket - skc_family and the
sk_kern_sock bit - come from here instead, taken from the device BTF.
"""
from btfutil import here, load_base, find_structs, member, resolve

base, _ = load_base()
socks = find_structs(base, "sock", 1, len(base) + 1)
assert len(socks) == 1, socks
sock = socks[0]

fam_bit, fam_bits, fam_type = member(base, sock, ["__sk_common", "skc_family"])
fam_int = base[resolve(base, fam_type)]
assert fam_bits == 0 and fam_bit % 8 == 0 and fam_int["kind"] == 1 and fam_int["value"] == 2, \
    "skc_family must be a byte-aligned 2-byte integer"

kern_bit, kern_bits, _ = member(base, sock, ["sk_kern_sock"])
assert kern_bits == 1, "sk_kern_sock must be a 1-bit field"

out = here / ".build"
out.mkdir(exist_ok=True)
(out / "sbo_sock_layout.h").write_text(
    "/* Generated by gen_layout.py from the device vmlinux BTF. Do not edit. */\n"
    f"#define SBO_SOCK_SIZE {base[sock]['value']}\n"
    f"#define SBO_SKC_FAMILY_OFFSET {fam_bit // 8}\n"
    f"#define SBO_SK_KERN_SOCK_BYTE {kern_bit // 8}\n"
    f"#define SBO_SK_KERN_SOCK_SHIFT {kern_bit % 8}\n"
)
print(f"sock size={base[sock]['value']} skc_family@{fam_bit // 8} sk_kern_sock@{kern_bit // 8}.{kern_bit % 8}")
